import axios from 'axios';

export function getAccesToken(clientId, clientSecret) {
    return axios.post("https://sandbox.livevol.com/id/connect/token",
    "grant_type=client_credentials",
    {
        headers: {
            Authorization: "Basic " + btoa(clientId+':'+clientSecret),
            "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
        },
    });
}

export function getCashSecuredPuts(accessToken, symbols) {
    // const symbols = "DDD,MMM,ABT,ABBV,ANF,ACAD,ACN,ATVI,ADBE,AMD,AFL,AGNC,AKAM,AA,ALXN,BABA,ALGN,ADS,APT,GOOGL,GOOG," + 
    // "AMLP,MO,AMRN,AMZN,AMBA,AMC,AAL,AEO,AXP,AIG,AMT,ABC,AMGN,ADI,BUD,NLY,ANTM,APA,APHA,APO,AAPL,AMAT,AAOI,MT,ADM,ANET," + 
    // "AZN,T,TEAM,ACB,ADSK,ADP,AZO,BIDU,BK,VXX,GOLD,BHC,BAX,BDX,BBBY,BRK.B,BBY,BYND,BIIB,BAC,BB,BLK,BX,BA,BKNG,BSX,BP,BMY," + 
    // "AVGO,BURL,COG,CZR,CCJ,CPB,CWH,GOOS,CSIQ,CGC,COF,CPRI,CAH,KMX,CCL,CVNA,CAT,CBOE,VIX,CNC,CNP,CF,CHTR,CC,LNG,CVX,CHWY," +
    // "CMG,CIEN,CI,CRUS,CSCO,C,CTXS,CLF,CLX,CLDR,NET,CLVS,CME,CODX,KO,CTSH,CL,CMCSA,CYH,CAG,CXO,COP,ED,STZ,CSTM,CLR,GLW," + 
    // "COST,COTY,COUP,CREE,CRSP,CRON,CRWD,CSX,CMI,CVS,CYBR,DHI,DDOG,PLAY,DVA,ASHR,DE,DAL,DB,DVN,DKS,BRZU,FAZ,DUST,JNUG," + 
    // "LABD,TZA,TECS,YINN,ERX,FAS,NUGT,JDST,TNA,LABU,DFS,DISH,DIS,DOCU,DG,DLTR,DPZ,DOW,DKNG,DBX,DD,DJX,KODK,ETN,EBAY," + 
    // "EDIT,EW,EA,EMR,ENDP,ET,EPD,EOG,JETS,ETSY,EXAS,EXPE,XOM,FFIV,FB,FSLY,FDX,RACE,FCAU,FEYE,AG,FSLR,FISV,FIT,FIVE," +
    // "FLEX,FLR,FL,F,FOSL,FOXA,FCX,GME,GPS,GD,GE,GM,GNUS,GNW,GILD,GSK,GREK,GS,GT,GPRO,GRPN,GRUB,GPOR,HAL,HBI,HOG,HIG," + 
    // "HAS,HCA,HL,HLF,HSY,HTZ,HES,HPE,HIMX,HFC,HD,HON,HRL,HPQ,HSBC,HUM,HUYA,HYLN,ITW,ILMN,IMMU,INFN,INO,INTC,IBM,IP,INTU" +
    // ",ISRG,FXE,FXY,UUP,TAN,QQQ,IQ,IRBT,IAU,EWZ,EWH,EWJ,EWW,EWY,SLV,SHY,TLT,IEF,FXI,IVV,HYG,LQD,EFA,EEM,INDA,EWU,IBB,IWF,IWM,IYR,ITB,JBL,JD,JNJ,JCI,YY,JPM,JNPR,KSU,KEY,KMB,KMI,KGC,KKR,KLAC,KSS,KHC,KR,LB,LRCX,LVS,LEN,LBTYA,LBTYK,LLY,LVGO,LMT,LOW,LULU,LL,LUMN,LITE,LYFT,LYB,M,MNKKQ,MNKD,MRO,MPC,MAR,MRVL,MA,MTCH,MAT,MCD,MCK,MDT,MELI,MRK,MET,MGM,MCHP,MU,MSFT,MRNA,TAP,MOMO,MDLZ,MDB,MNST,MS,MOS,MXEF,MXEA,MYL,XSP,NDX,NOV,NAV,NKTR,NTAP,NTES,NFLX,NBEV,NEM,NKE,NKLA,NIO,NOK,JWN,NSC,NOC,NCLH,NVAX,NRG,NUE,NTNX,NTR,NVDA,NXPI,OXY,OKTA,OLN,OKE,OPK,ORCL,OSTK,PLTR,PANW,PZZA,PYPL,PTON,PENN,PEP,PBR,PFE,PCG,PM,PSX,PDD,PINS,PXD,PAA,PLUG,PNC,PPG,PG,SVXY,UCO,UVXY,VIXY,SSO,TBT,TQQQ,SPXU,SQQQ,SDS,UPRO,PHM,QCOM,RRC,RTX,REGN,RVLV,RH,RNG,RIOT,RAD,RKT,ROKU,ROST,RCL,RDS.A,RUT,OEX,XEO,SPGI,SAGE,CRM,SRPT,SLB,SCHW,SGMS,SE,STX,SEAS,XLC,XLE,XLY,XLP,XLV,XLF,XLI,XLU,XLB,XLK,NOW,SHAK,SHOP,SIG,SIRI,SKX,SWKS,WORK,SDC,SNAP,SNOW,SNE,SRNE,SO,LUV,SWN,DIA,GLD,FEZ,SPY,MDY,JNK,XBI,XHB,XME,XOP,KRE,XRT,SPLK,SPOT,SPX,SQ,STMP,SWK,SBUX,SFIX,STNE,SSYS,SU,SPWR,SYF,SYY,TMUS,TSM,TTWO,TNDM,TPR,TGT,TTM,TECK,TDOC,THC,TSLA,TEVA,TXN,TTD,TIF,TLRY,TJX,TOL,TSCO,RIG,TRIP,TWLO,TWTR,TSN,UBER,ULTA,UAA,UA,UNP,UAL,UPS,URI,X,UNG,USO,UNH,OLED,URBN,USB,VFC,VALE,VLO,GDX,GDXJ,OIH,RSX,SMH,VWO,VXRT,VZ,VRTX,VIAC,VIPS,SPCE,V,VMW,VOD,WBA,WMT,W,WB,WFC,WDC,WY,WPM,WHR,WMB,EPI,WDAY,WKHS,WW,WYNN,XLNX,AUY,YNDX,YELP,YETI,YPF,YUM,Z,ZTS,ZM,ZS,ZNGA";
    
    // const symbols = "AMD,BA,DOW,AIG,WYNN,AAPL"
    
    return axios.put("https://sandbox.livevol.com/api/v1/delayed/market/scans/options/cash-secured-puts",
    {
        "out_of_the_money": 5.0,
        "option_bid": 0.25,
        "hv30_min": null,
        "hv30_max": null,
        "high_low_stock_min": null,
        "high_low_stock_max": null,
        "time_frame": "short",
        "industry_codes": null,
        "symbols": symbols,
        "stock_price_min": 10.0,
        "stock_price_max": 200.0
    },
    {
        headers: {
            Authorization: "Bearer " + accessToken
        }
    });
}
